//
// Created by m2 on 2/5/21.
//

#include "UiRegistry.h"
#include "gtkmm.h"

UiRegistry::UiRegistry() {}

Glib::ustring UiRegistry::getUString() {
    return (Glib::ustring) "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                           "<!-- Generated with glade 3.22.2 -->\n"
                           "<interface>\n"
                           "  <requires lib=\"gtk+\" version=\"3.20\"/>\n"
                           "  <object class=\"GtkDialog\" id=\"dialog\">\n"
                           "    <property name=\"can_focus\">False</property>\n"
                           "    <property name=\"type_hint\">dialog</property>\n"
                           "    <child type=\"titlebar\">\n"
                           "      <placeholder/>\n"
                           "    </child>\n"
                           "    <child internal-child=\"vbox\">\n"
                           "      <object class=\"GtkBox\" id=\"box\">\n"
                           "        <property name=\"can_focus\">False</property>\n"
                           "        <property name=\"orientation\">vertical</property>\n"
                           "        <property name=\"spacing\">2</property>\n"
                           "        <child internal-child=\"action_area\">\n"
                           "          <object class=\"GtkButtonBox\" id=\"button-box\">\n"
                           "            <property name=\"can_focus\">False</property>\n"
                           "            <property name=\"layout_style\">end</property>\n"
                           "            <child>\n"
                           "              <object class=\"GtkButton\" id=\"button-cancel\">\n"
                           "                <property name=\"label\" translatable=\"yes\">cancel</property>\n"
                           "                <property name=\"visible\">True</property>\n"
                           "                <property name=\"can_focus\">True</property>\n"
                           "                <property name=\"receives_default\">True</property>\n"
                           "              </object>\n"
                           "              <packing>\n"
                           "                <property name=\"expand\">True</property>\n"
                           "                <property name=\"fill\">True</property>\n"
                           "                <property name=\"position\">0</property>\n"
                           "              </packing>\n"
                           "            </child>\n"
                           "            <child>\n"
                           "              <object class=\"GtkButton\" id=\"button-ok\">\n"
                           "                <property name=\"label\" translatable=\"yes\">ok</property>\n"
                           "                <property name=\"visible\">True</property>\n"
                           "                <property name=\"can_focus\">True</property>\n"
                           "                <property name=\"receives_default\">True</property>\n"
                           "              </object>\n"
                           "              <packing>\n"
                           "                <property name=\"expand\">True</property>\n"
                           "                <property name=\"fill\">True</property>\n"
                           "                <property name=\"position\">1</property>\n"
                           "              </packing>\n"
                           "            </child>\n"
                           "          </object>\n"
                           "          <packing>\n"
                           "            <property name=\"expand\">False</property>\n"
                           "            <property name=\"fill\">False</property>\n"
                           "            <property name=\"position\">1</property>\n"
                           "          </packing>\n"
                           "        </child>\n"
                           "        <child>\n"
                           "          <placeholder/>\n"
                           "        </child>\n"
                           "      </object>\n"
                           "    </child>\n"
                           "  </object>\n"
                           "</interface>";
}
